### ISSUE TITLE
Imports are not to be watched

### ISSUE THREAD

**Issue by droooney** [xiaofuzi/rollup-plugin-less#2]
If you use this plugin with rollup-watch (I don't know if it's related to this plugin or rollup-watch) the files you import are not to be watched. For example if you have:

```less
// main.less
@import './mixins';

body {
  .hidden();
}
```

```less
// mixins.less
.hidden {
  display: none;
}
```
and if you change mixins.less the watch process does not reflect. Can you please look into that and tell if I should report the issue there (rollup-watch) or it's related to rollup-plugin-less?

**Comment by xiaofuzi** [comment]
it seems that the rollup-watch only watch the files you import directly.
